### ISSUE TITLE
Basics of Serverless Architecture

### ISSUE THREAD

**Issue by larry-dalmeida** [larry-dalmeida/startup-curriculum#1]
# What I want to learn

- [ ] AWS Lambda
- [ ] API Gateway
- [ ] Serverless Offline
- [ ] TypeScript Support
- [ ] Test Lambda Locally
- [ ] Github Actions

# The App

Web App that generates conversation topics for German language learners.

# Work Packages

- [ ] Frontend
  - [ ] React App with TypeScript
  - [ ] Mock DB with Data (topics grouped by CEFR Level)
  - [ ] Deploy with Serverless CLI
  - [ ] Deploy with Github Actions
- [ ] Backend
  - [ ] AWS Lambda with Hardcoded Data
    - [ ] Randomly select a topic for a given CEFR Level
  - [ ] API Gateway to respond to incoming request and call the Lambda
  - [ ] AWS Dynamo DB setup
